### PR TITLE
Add array-check to fix Session-Warnin

### PR DESCRIPTION
**Pull request by xstable**
PHP Warning:  Invalid argument supplied for foreach() in xxxxx/contenido/classes/class.session.php on line 226

### CODE REVIEW

**Comment by oldperl** [comment]
Hi,

i would not use this fix, see my post in forum >> https://forum.contenido.org/viewtopic.php?p=180681#p180681

**Comment by tone2tone** [comment]
The development branch version of this file has significantly changes since the ticket was created. 
The 4.10.0 version segment started at line 224, reading:
```
                $str .= "\$$var = array(); ";
                eval("\$l = array(); foreach(\$$var as \$k => \$v) {\$l[] = array(\$k,gettype(\$k),\$v);}");
```
The development branch version starts at 204, reading:
```
                $str .= "\${$var} = [];\n";
                eval("\$l = []; foreach (\${$var} as \$k => \$v) { \$l[] = [\$k, gettype(\$k), \$v]; }");
```
Again, I think that in the development branch version both arrays aren't properly instantiated and should be changed to:
```
                $str .= "\${$var} = array();\n";
                eval("\$l = array(); foreach (\${$var} as \$k => \$v) { \$l[] = [\$k, gettype(\$k), \$v]; }");
```

**Comment by muratpurc** [comment]
@tone2tone  The code in the development branch is identically to your proposal. It uses the short array syntax, which is availabe since PHP 5.4.
I don't see a reason to use old array syntax here.

**Comment by tone2tone** [comment]
Ah ok, Didn't know about this shortcut and seemed to me as if the array was about to be instantiated through an element. 
So then, what does it need to check or test this pull request?

**Comment by muratpurc** [comment]
@tone2tone oldperl already gave feedback in the pr, and I'm not shure how it is possible that the variable is not an array, although the code few lines before detemines it as an array.
It would be great to have a step by tep introduction, which confirmes that there is a bug and that the change in the pr fixes it.

**Comment by tone2tone** [comment]
First of all, in all my actual 4.10.1 log files, I never see any of those foreach-errors for class.session.php as mentioned in the forum. 
Generally I do not understand how the determination of $$var-type is really made and comes to conclusions, but that's not essential to come to conclusions. I dumped all $var variables before they are used in $$var and then I dumped which of the $$var variables made it to the "it's an array" switch case. 
I then var_dumped all $l-arrays that are newly built in the switch case, and ALL $l-arrays are properly built up, filled and exist, saying: the foreach-functionality is working correctly IMHO.

**Comment by gonatan** [comment]
Will it be possible to write a unit test that shows the problem?

**Comment by dceonline** [comment]
Closed because of inactivity. Please reopen if error persists.

**Pull request closed without merging**
