### PR TITLE
#48 Layout change in templates keeps maximum of possible module confi…

### PR DESCRIPTION
**Pull request by tone2tone**
…guration

Here's my approach to solving the problem; read more in item correspondence.
Basically, instead of just deleting all container->module relations, this version tries to keep as much as possible, but it still abandons all container-module-relations for containers that are no more present in the new layout. 
There is no intense checking on whether or not the type of module fits into this container or not, so this solution is not perfect. It suits the needs of must usecases and reduces the re-configuration work for editors if two layouts are very similar to one another, relying on identical container IDs.

### CODE REVIEW

**Comment by tone2tone** [comment]
@purcaholic I have a handling problem here. I pushed #40 Teaser module into this pull request and have NO idea how to call it back, sorry. Is there ANY chance you can ignore this second commit or delete it? I called back my commit in VS but it changed nothing in my own repository nor here. Still not really good in handling GIT, sorry.

**Comment by muratpurc** [comment]
@tone2tone I don't think that we can exclude commits. The pull request was made made from the branch `bug/#48-templates-module-configuration-gets-lost-after-layout-change` and this branch containd two commits.

But you can do following steps:
- Save your changes made in your branch
- Remove the pull request
- Delete your branch
- Create a new branch with the same name
- Commit the change to the branch
- Create a new pull request

Maybe there is a more elegant solution for this, if so, then I don't know it.

**Comment by tone2tone** [comment]
@purcaholic My problem is: I do not know how to "remove the pull request". I find no button and no menu for it and do not know what VS Code function is equivalent to "remove a pull request". .... :-/ Do you mean that i "close the pull request" as shown on button of this page or something else?

**Comment by muratpurc** [comment]
@tone2tone sorry, my mistake, here is an introduction for closing a pull request:
https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/closing-a-pull-request

**Comment by tone2tone** [comment]
Okay, with closing the pull request and deleting the branch in my rep and in VS Code, my VS Code is totally fucked up now. Nothing works anymore. It constantly wants me to merge something for the deleted branch and I am stuck. I can't open new branches, don't know HOW to consolidate matters here or how to proceed. Sometimes this system is really not helping in solving problems, just tells you that you have some, but not what to do.

**Pull request closed without merging**
