### PR TITLE
Update functions.general.php because second argument in str_repeat() cannot be smaller than 0

### PR DESCRIPTION
**Pull request by Faar400**
PHP Warning:  str_repeat(): Second argument has to be greater than or equal to 0 in line 1186

### CODE REVIEW

**Comment by muratpurc** [comment]
Similar logic is used several times in the project and therefore it should be fixed/adjusted everywhere.

Please follow the coding guidelines, use braces for if-statements, use a whitespace before and after round brackets, don't write a if condition in one line.

**Comment by dceonline** [comment]
Please format the code like this from
` if($props["level"] < 1)$props["level"] = 1;`
to
`if($props["level"] < 1) {
     $props["level"] = 1;
}`
due to our coding conventions.

**Comment by dceonline** [comment]
So i have one more question. Do we need such type of comment?
That the second param has to be 0 is given by the php function, the warning isn't thrown anymore and who has done it is written in the commit. I think we have to reduce unneeded comments to get [clean code](https://github.com/jupeter/clean-code-php).

**Comment by dceonline** [comment]
@Faar400 
I now checked the whole function, and recoded it, so i also save not needed db requests. Can you please check the code for functions.general.php in the attached archive and give me some feedback?
[functions.general.zip](https://github.com/CONTENIDO/CONTENIDO/files/8662653/functions.general.zip)

**Comment by Faar400** [comment]
I have to test it.
And have to test with max(0,...), because if "level" has 0 in the database, what happens if i set `$props["level"] =1` ?
Because only for str_repeat()'s second parameter calculation `$props["level"]-1` should not be 0, perhaps better "-1" should be a variable like $dingens, which is 0 if "level" is 0.
So $props["level"] can leave 0.

**Comment by dceonline** [comment]
> Because only for str_repeat()'s second parameter calculation `$props["level"]-1` should not be 0

well, my recoded function dont use str_repeat any more, and i  also dont calculate anything with -1.
Just try and see.

**Comment by Faar400** [comment]
@purcaholic @dceonline I changed the code a bit, intending not to change the content of the array variable but the level correction number 1.
This is now a variable that is 1 by default and also becomes 0 when Level = 0 occurs.

**Pull request closed without merging**
