### PR TITLE
recode and optimize mysql queries in function buildCategorySelect

### PR DESCRIPTION
**Pull request by dceonline**
I have recoded this function to minimize mysql requests. Maybe we have to set new index for tables.

### CODE REVIEW

**Comment by dceonline** [comment]
@purcaholic , i' ve just two questions.

In function indent, why do u only secure the first int param with class cSecurity and not also the other params?

And in function buildCategorySelect, why do u use $aIdCat directly in sql-statement and don't use the mysql generation for this var to?

**Comment by muratpurc** [comment]
@dceonline 

> In function indent, why do u only secure the first int param with class cSecurity and not also the other params?

Good point, all of them should be casted to integer.

> And in function buildCategorySelect, why do u use $aIdCat directly in sql-statement and don't use the mysql generation for this var to?

The variable `$aIdCat` is a concatenated string and represents the list of category ids to be used for the `IN()` function. I did not want to pass the `$aIdCat` as a parameter to the `query` function because the function would escape it, since it would be treated as a string.  It is not a good idea to pass generated sql statement parts as a replacement parameter to the `query` function, this can result in unwanted side-effects.

By the way, I'm still waiting for your answers to my questions...

**Comment by dceonline** [comment]
@purcaholic which questions do you mean?

**Comment by muratpurc** [comment]
@dceonline all of my comments to your pr are in pending mode.
image

This explains the missing feedback.

**Comment by dceonline** [comment]
@purcaholic 
Hi Murat,
well, where do i find this view? I will answer u in future, if i know where i have to do this.

**Comment by muratpurc** [comment]
@dceonline I don't know, may be it requires some action from my side. I made some comments but did not submit the review, this could be the reason for the pending state. GitHub pull requests seem to behave different than the Bitbucket ones.

It was my fault most likely, sorry for causing troubles.

**Pull request merged**
