### PR TITLE
#264 Resolve redundant admin checks.

### LINKED ISSUE #264: Resolve redundant admin checks
We use following or similar code several times in the project:

```
    $auth = cRegistry::getAuth();
    $aAuthPerms = explode(',', $auth->auth['perm']);

    $admin = false;
    if (count(preg_grep("/admin.*/", $aAuthPerms)) > 0) {
        $admin = true;
    }
```

Resolve the redundancy of this admin checks.

### PR DESCRIPTION
**Pull request by muratpurc**
- Moved admin checks into in cPermission
- Added isAdmin() method to cPermission
- Added static methods to cPermission to do common checks
- Unit tests for the new methods in cPermission
- Added prepare() method to cItemBaseAbstract to do similar sql statement replacements like in cDbDriverHandler::prepare()

### CODE REVIEW

**Review by dceonline — CHANGES_REQUESTED** [review]
Are we sure that renamed methods in permission class are not use by anybody else than the core of CONTENIDO?
Maybe it's a better way to mark old method deprecated and add new method with fixed typo. Deprecations should then be removed with the next version or the one after that.

We should also use this behaviour for other changes of typos if methods are not marked as private.

**Comment by muratpurc** [comment]
@dceonline I agree with you that we should always mark public method names and public class properties as deprecated whenever we rename them.

But in this case, I've changed the upper and lower case of some method names, marking the previous method names as deprecated wouldn't work, since method names are not case sensitive in PHP. The method names `getIDForAction` and `getIdForAction` are the same for PHP.

**Review by gonatan — APPROVED** [review]
That's fine for me. Two things I would have done in a different way though.

Calling static methods like $perm::checkAdminPermission works as expected but cPermission::checkAdminPermission is more straightforward.

Instead of the "check" prefix for the new cPermission methods I would have used "has" like the existing method "hasClientPermission" does.

Good work!

**Comment by muratpurc** [comment]
@gonatan Thank you for the feedback. I've used the `check` prefix to not get naming conflicts with the `has` prefix, which is already in use by the instance method `hasClientPermission`.

**Pull request merged**
